source /home/altay/miniconda3/etc/profile.d/conda.sh
conda activate scATAcat_reproducibility_env
python3 /project/scATAC_analysis/scATAcat_review/preprocessing/Satpathy2019/Bone_Marrow_Rep1_scATAC/04_preprocessing_for_EpiAnno/get_Granja2019_BMMC_unified_peak_matrix/02a_create_query_peaks_per_cell_matrix.py