source /home/altay/miniconda3/etc/profile.d/conda.sh
conda activate scATAcat_reproducibility_env
python3 /project/scATAC_analysis/scATAcat_review/preprocessing/Zhu2023_brain_scmultiome/01_preprocessing_for_EpiAnno/get_Morabito2021_brainCortex_unified_peak_matrix/02a_create_query_peaks_per_cell_matrix.py